name: Push to Another Repo

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      # If you need to make changes to files or run build steps, add them here

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Generate a new SSH key pair if you want to use SSH-based authentication
      - name: Add remote repository
        run: |
          git remote add target-repo https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com:EpitechMscProPromo2025/T-ESP-901-60294-BDX-Untitled-Tek-Game-2.git
          git fetch target-repo

      # This will push the changes to the target repository
      - name: Push to target repository
        run: |
          git push target-repo main

    # Optionally, use a different branch in the target repo:
    # git push target-repo main:target-branch
