name: Push to Another Repo Using SSH

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      # Set up SSH agent and add the private key from the GitHub secret
      - name: Setup SSH for pushing to another repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Set up Git user for commits
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Add the target repository via SSH
      - name: Add target repository remote
        run: |
          git remote add target-repo git@github.com:EpitechMscProPromo2025/T-ESP-901-60294-BDX-Untitled-Tek-Game-2.git
          git fetch target-repo
          git pull target-repo

      # Push changes to the target repository
      - name: Push changes to target repository
        run: |
          git push target-repo main

    # Optionally, specify a different branch in the target repo if necessary
    # git push target-repo main:target-branch
